### ISSUE TITLE
不知道为什么 0.3之后的版本都用不了

### ISSUE THREAD

**Issue by Annnnh1010** [synctv-org/synctv#169]
![VeryCapture_20240520232015](https://github.com/synctv-org/synctv/assets/76246787/aa7f7382-07ee-4203-91d7-7df04ff73c9b)

**Comment by zijiren233** [comment]
什么架构

**Comment by Annnnh1010** [comment]
openwrt docker
![image](https://github.com/synctv-org/synctv/assets/76246787/c5020793-6cd4-45af-abbe-8160bc33141b)

**Comment by zijiren233** [comment]
cpu是amd64/x86_64吗？

**Comment by Annnnh1010** [comment]
是的

**Comment by Annnnh1010** [comment]
runtime.gopark(0x198?, 0x2df7d40?, 0x1?, 0x2?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00005e620 sp=0xc00005e600 pc=0x43f0ce
runtime.runfinq()
	runtime/mfinal.go:193 +0x107 fp=0xc00005e7e0 sp=0xc00005e620 pc=0x41e347
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x46f2c1
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:163 +0x3d
goroutine 4 [GC worker (idle)]:
runtime.gopark(0xd9a08299e53e?, 0x3?, 0xd3?, 0xf?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00005f750 sp=0xc00005f730 pc=0x43f0ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00005f7e0 sp=0xc00005f750 pc=0x420ee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x46f2c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c
goroutine 34 [GC worker (idle)]:
runtime.gopark(0xd9a1e8baf4c4?, 0x3?, 0xc?, 0x8d?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000804750 sp=0xc000804730 pc=0x43f0ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0008047e0 sp=0xc000804750 pc=0x420ee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0008047e8 sp=0xc0008047e0 pc=0x46f2c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c
goroutine 20 [GC worker (idle)]:
runtime.gopark(0xd9a1e9b027b1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00005b750 sp=0xc00005b730 pc=0x43f0ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00005b7e0 sp=0xc00005b750 pc=0x420ee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005b7e8 sp=0xc00005b7e0 pc=0x46f2c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c
goroutine 5 [GC worker (idle)]:
runtime.gopark(0xd9a1e9bd997b?, 0x1?, 0xc1?, 0x8b?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00005ff50 sp=0xc00005ff30 pc=0x43f0ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00005ffe0 sp=0xc00005ff50 pc=0x420ee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x46f2c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c
goroutine 50 [chan receive]:
runtime.gopark(0x45b59e?, 0xc00004e500?, 0x8?, 0xe0?, 0xd9a2637aec7e?)
	runtime/proc.go:398 +0xce fp=0xc00005c6d0 sp=0xc00005c6b0 pc=0x43f0ce
runtime.chanrecv(0xc0002502a0, 0x0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc00005c748 sp=0xc00005c6d0 pc=0x40afad
runtime.chanrecv1(0x77359400?, 0x0?)
	runtime/chan.go:442 +0x12 fp=0xc00005c770 sp=0xc00005c748 pc=0x40abb2
github.com/Boostport/mjml-go.periodicallyRemoveIdleResources(0x0?)
	github.com/Boostport/mjml-go@v0.14.6/pool.go:61 +0x3e fp=0xc00005c7c8 sp=0xc00005c770 pc=0x1314d3e
github.com/Boostport/mjml-go.init.0.func1()
	github.com/Boostport/mjml-go@v0.14.6/mjml.go:67 +0x25 fp=0xc00005c7e0 sp=0xc00005c7c8 pc=0x13133a5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x46f2c1
created by github.com/Boostport/mjml-go.init.0 in goroutine 1
	github.com/Boostport/mjml-go@v0.14.6/mjml.go:67 +0x296
goroutine 51 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00005ced0 sp=0xc00005ceb0 pc=0x43f0ce
runtime.chanrecv(0xc00012afc0, 0xc00005cfa0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc00005cf48 sp=0xc00005ced0 pc=0x40afad
runtime.chanrecv2(0x0?, 0x0?)
	runtime/chan.go:447 +0x12 fp=0xc00005cf70 sp=0xc00005cf48 pc=0x40abd2
github.com/zijiren233/gencontainer/synccache.NewSyncCache[...].func1()
	github.com/zijiren233/gencontainer@v0.0.0-20240507135401-7a9c8355bb2c/synccache/synccache.go:32 +0x9f fp=0xc00005cfe0 sp=0xc00005cf70 pc=0x132335f
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46f2c1
created by github.com/zijiren233/gencontainer/synccache.NewSyncCache[...] in goroutine 1
	github.com/zijiren233/gencontainer@v0.0.0-20240507135401-7a9c8355bb2c/synccache/synccache.go:31 +0xdc
rax    0xc005300000
rbx    0xc0052b4850
rcx    0xff410
rdx    0xff410
rdi    0xff420
rsi    0x1980000
rbp    0xc000ea75b8
rsp    0xc000ea75a0
r8     0xb
r9     0xc000dae060
r10    0x0
r11    0xd62ee0
r12    0x0
r13    0x7fe491a48c68
r14    0xc000dae060
r15    0xff420
rip    0x7fe491cd50a5
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0

**Comment by zijiren233** [comment]
具体原因不清楚
用的是什么型号的cpu？

**Comment by Annnnh1010** [comment]
![image](https://github.com/synctv-org/synctv/assets/76246787/0ec610c2-22c0-4cc9-853a-6058f437167c)
